config/routes.rb
Rails.application.routes.draw do
  root 'application#index'

  get 'sitemap.xml', :to => 'application#sitemap', :defaults => {:format => 'xml'}


  #search
  get 'search', to: 'search#search'

  #flat pages
  get 'about', to: 'application#about'
  get 'contact', to: 'application#contact'
  get 'rules', to: 'application#rules'
  get 'privacy', to: 'application#privacy'
  get 'getinvolved', to: 'application#getinvolved'
  get 'fundraising', to: 'application#fundraising'
  
  get 'compare', to: 'teams#compare'

  #awards
  get 'awards', to: 'application#awards'

  #newsletters
  get 'newsletters', to: 'campaigns#index'

  #standard index routes
  get 'teams', to: 'teams#index'
  get 'charges', to: 'charges#index'
  #get 'sponsors', to: 'sponsors#index'
  get 'beneficiaries', to: 'beneficiaries#index'

  #cars
  get 'cars', to: 'cars#index'
  get 'car/:ref', to: 'cars#show'

  #photos
  get 'photo/:id', to: 'photos#show'
  get 'admin/photo_views', to: 'photos#views'
  get 'photos', to: 'photos#index'

  #JSON STUFF
  get ':id/guards',constraints: {id: /\d{4}/}, to: 'guards#json_index'
  get ':id/entries',constraints: {id: /\d{4}/}, to: 'entries#json_index'
  get 'entry/:entry_id',to: 'entries#json_show'
  get 'entry_legs/:entry_id', to: 'entry_legs#json_index'
  get 'leg/:leg_id',to: 'legs#json_show'

  #charge by year
  get ':id', constraints: {id: /\d{4}/}, to: 'charges#show'

  #charge team list
  get ':id/teams', constraints: {id: /\d{4}/}, to: 'entries#index'

  #charge photos
  get ':id/photos', constraints: {id: /\d{4}/}, to: 'charges#photos'


  #team by name (ref)
  get ':ref', to: 'teams#show'
  get ':ref/photos', to: 'teams#photos'
  #team compare
  get 'compare/:teamone/:teamtwo', to: 'teams#compare'


  #entry by year and team
  get ':id/:ref',constraints: {id: /\d{4}/}, to: 'entries#show'
  get ':id/:ref/photos',constraints: {id: /\d{4}/}, to: 'entries#photos'


  #team by name (ref)
  get 'teams/:id', to: 'teams#show'
  get 'team/:id', to: 'teams#show'

  #charge by year
  get 'charges/:id', to: 'charges#show'
  get 'charge/:id', to: 'charges#show'


  #beneficiary by name (ref)
  get 'beneficiaries/:id', to: 'beneficiaries#show'
  get 'beneficiary/:id', to: 'beneficiaries#show'

  #sponsor by name (ref)
  get 'sponsors/:id', to: 'sponsors#show'
  get 'sponsor/:id', to: 'sponsors#show'

  #cars by id
  get 'cars/:id', to: 'cars#show'
  get 'car/:id', to: 'cars#show'


end

app/models/entry.rb
class Entry < ApplicationRecord

  has_one :entry_geom
  belongs_to :charge, touch: true
  belongs_to :team
  belongs_to :car
  belongs_to :start_guard, foreign_key: 'start_guard_id', class_name: 'Guard'
  has_many :gps_raws
  has_many :gps_cleans
  has_many :gps_stops
  has_many :checkins
  has_many :entry_legs
  has_many :photos, as: :photoable

  scope :past,-> {includes(:charge).where("charges.has_result=true")}
  scope :current,-> {references(:charge).includes(:charge).where("charges.has_result=false").order("RANDOM()")}


  def first_for_team?
      self.charge==self.team.charges.order(:charge_date).first
  end

  def is_current?
    self.charge.has_result
  end

  def result_summary(limit=3)
    res=[]
    if self.charge.spirit_entry_id==self.id
      res<<[0,(Charge.awards(:spirit) + ' Spirit of the Charge'.html_safe)]
    end
    if self.charge.shafted_entry_id==self.id
      res<<[0.1,('Properly Shafted Award'.html_safe)]
    end
    if self.position_net_distance and self.position_net_distance<=limit
      res<<[self.position_net_distance,((self.position_net_distance ==1 ? Charge.awards(:net_distance) + ' - ' : '') +
          format_position(self.position_net_distance) + ' place for the shortest net distance').html_safe]
    end
    if self.position_net_bikes and self.position_net_bikes<=limit
      res<<[self.position_net_bikes,(
          format_position(self.position_net_bikes) + ' place for the shortest net distance for a bike team').html_safe]
    end
    if self.position_raised and self.position_raised<=limit
      res<<[self.position_raised+0.1,((self.position_raised==1 ? Charge.awards(:raised) + ' - ' : '') +
          format_position(self.position_raised) + ' place for most money raised for conservation').html_safe]
    end
    if !self.position_distance.nil? and self.position_distance<=limit
      res<<[self.position_distance+0.2,((self.position_distance==1 ? Charge.awards(:distance) + ' - ' : '') +
          format_position(self.position_distance) + ' place for the shortest overall distance').html_safe]
    end
    if self.position_bikes and self.position_bikes<=limit
      res<<[self.position_bikes+0.2,((self.position_bikes==1 ? Charge.awards(:bikes) + ' - ' : '') +
          format_position(self.position_bikes) + ' place for the shortest distance by a bike team').html_safe]
    end

    if self.position_gauntlet and self.position_gauntlet<=limit
      res<<[self.position_gauntlet+0.3,((self.position_gauntlet ==1 ? Charge.awards(:gauntlet) + ' - ' : '') +
          format_position(self.position_gauntlet) + ' place for the shortest distance on the gauntlet').html_safe]
    end
    if self.position_tsetse1 and self.position_tsetse1<=limit
      res<<[self.position_tsetse1+0.4,((self.position_tsetse1==1 ? Charge.awards(:tsetse1) + ' - ' : '') +
          format_position(self.position_tsetse1) + ' place for the shortest distance on tsetse line 1').html_safe]
    end
    if self.position_tsetse2 and self.position_tsetse2<=limit
      res<<[self.position_tsetse2+0.5,((self.position_tsetse2==1 ? Charge.awards(:tsetse2) + ' - ' : '') +
          format_position(self.position_tsetse2) + ' place for the shortest distance on tsetse line 2').html_safe]
    end
    if self.position_ladies and self.position_ladies<=limit
      res<<[self.position_ladies+0.6,((self.position_ladies==1 ? Charge.awards(:ladies)+ ' - ' : '') +
          format_position(self.position_ladies) + ' place for the shortest distance by a ladies team').html_safe]
    end
    if self.position_newcomer and self.position_newcomer<=limit
      res<<[self.position_newcomer+0.7,(
          format_position(self.position_newcomer) + ' place for the shortest distance by a new team').html_safe]
    end
    if self.position_international and self.position_international<=limit
      res<<[self.position_international+0.8,(
      format_position(self.position_international) + ' place for the shortest distance by an international team').html_safe]
    end

    res.sort{|x,y| x[0]<=> y[0]}.collect do |p|
        ("<div style='" + (p[0]<2 ? "" : "") + "'>" + p[1] + "</div>").html_safe
      end
  end

  def description
    txt=self.team.long_name + ' '
    unless self.name==self.team.name
      txt+=' entered as ' + self.name + ' '
    end
    txt+='in the ' + self.charge.name
  end

  def photo_random_landscape()
    Entry.uncached do
      pht=self.photos.order("RANDOM()").limit(1).first
    end
  end

  def start_time
    unless self.checkins.nil? or self.checkins.count==0
      self.checkins.order(:checkin_number).first.checkin_timestamp
    end
  end

  def raised_dollars
    unless self.raised_kwacha.nil?
      self.raised_kwacha/self.charge.exchange_rate
    else
      0
    end
  end

  def types_description
    type=[]
    type << 'Ladies' if self.is_ladies
    type << 'New Entry' if self.is_newcomer
    type << 'International' if self.is_international
    type << 'Bikes' if self.is_bikes
    type << '' if type.count==0
    type.join(', ')
  end

  protected

end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController

  def json_index
    charge=Charge.find_by_ref(params[:id])
    @entries=charge.entries.order(:car_no)
    render json: @entries
  end

  def index
    @charge=Charge.find_by_ref(params[:id]) or not_found
    @entries=@charge.entries.order(:car_no)
    if @charge.is_current?
      @grants=Charge.past.order(:charge_date).last.grants.order("RANDOM()")
    else
      @grants=@charge.grants.order("RANDOM()")
    end
  end

  def json_show
    @entry=Entry.find(params[:entry_id])
    render json: @entry
  end

  def show
    @charge=Charge.find_by_ref(params[:id])  or not_found
    @team=Team.find_by_ref(params[:ref]) or not_found

    @entry=Entry.joins(:charge,:team).where("charges.ref=? and teams.ref=?",@charge.ref,@team.ref).first

    @photo=@entry.photos.is_car.order("RANDOM()").first
    if @photo.nil?
      @photo=@entry.car.photos.order("RANDOM()").first
    end
    @entry_legs=@entry.entry_legs.joins(:leg).order(:leg_number)
    @min_elev=@charge.elevation_min/100*100
    @max_elev=(@charge.elevation_max/100*100)+100
    @results=@entry.result_summary(1000)
  end
  def photos
    @charge=Charge.find_by_ref(params[:id])
    @team=Team.find_by_ref(params[:ref])

    @entry=Entry.joins(:charge,:team).where("charges.ref=? and teams.ref=?",@charge.ref,@team.ref).first

  end
end

app/views/entries/_entry_description.erb
Raised <%= bold { '$' + number_with_precision(entry.raised_dollars, precision: 0, delimiter: ',') } %> in their <%= bold { format_position2(entry.entry_no) } %> charge.

<% if entry.result_description=='Complete'%>
    <b>Finished</b> the course in
<% else %>
    Completed <%= entry.result_guards %> of <%= entry.charge.guards.count+1 %> checkpoints for
<% end %>
<% if entry.is_bikes %>
    <%= bold { format_position2(entry.position_bikes) }%> place.
<% else %>
    <%= bold { format_position2(entry.position_distance) }%> place.
<% end %>

app/views/entries/_entrycard.erb
<div class="card">

    <div class="card-header">
        <a href="<%= entry_path entry %>">
      <h6><b><%= entry.car_no%></b> <%= entry.team.long_name %></h6>
      </a>
    </div>

  <div class="card-block" style="padding:5px;">
    <%
      photo=entry.photo_random_landscape
      p=render :partial => 'photos/photo', :locals => {:photo => photo}
    %>
    <%=
      if photo
        link_to p,photo_path(photo) + '?return=' + request.path
      else
        p
      end
    %>
  </div>
  <div class="card-block" style="text-align: center;padding-top:0px;">
    <%= render :partial => 'entries/entry_description', :locals => {:entry => entry} %>

  </div>
</div>

app/views/entries/index.html.erb
<% title('EC ' + @charge.ref + ' Teams') %>

<% breadcrumb [["charges","Charges"],[charge_path(@charge).sub!('/',''),'Elephant Charge ' + @charge.ref],[charge_entries_path(@charge).sub!('/',''),'Teams']] %>

<div class="container-fluid">
  <div class="row">
    <div class="col-lg-8">
      <div class="card">
        <div class="card-header">
          <div>
            <h5 style="display:inline-block;"><%= @charge.long_name %></h5>
            <div style="float:right;display: block;">
              <a data-toggle="tooltip" data-placement="top" title="Results" href="<%= charge_path(@charge) %>"><img style="margin-left:10px;" src="<%= image_path('icons/grey/results.png') %>"></a>
              <a data-toggle="tooltip" data-placement="top" title="Teams" href="<%= charge_entries_path(@charge) %>"><img style="margin-left:10px;" src="<%= image_path('icons/color/car.png') %>"></a>
              <% unless @charge.is_current? %>
                <a data-toggle="tooltip" data-placement="top" title="Photo Gallery" href="<%= charge_photos_path(@charge) %>"><img style="margin-left:10px;" src="<%= image_path('icons/grey/camera.png')%>"></a>
              <% end %>
            </div>
            <% unless @charge.is_current? %>
                <div>
                  <div style="float:right;display: block;">
                    <a data-toggle="tooltip" data-placement="top" title="Download Google Earth Tracks" href="<%= '/system/charges/kml/elephant_charge_' + @charge.ref + '.kml' %>"><img style="margin-left:10px;" src="<%= image_path('icons/grey/googleearth.png') %>"></a>
                    <a data-toggle="tooltip" data-placement="top" title="Download Detailed Results" href="<%= '/system/charges/xlsx/ElephantCharge_' + @charge.ref + '.xlsx' %>"><img style="margin-left:10px;" src="<%= image_path('icons/grey/excel.png') %>"></a>
                    <a data-toggle="tooltip" data-placement="top" title="Download The Charge Map" target="_blank" href="<%= @charge.map(:original) %>"><img style="margin-left:10px;" src="<%= image_path('icons/grey/map.png') %>"></a>
                  </div>
                </div>
            <% end %>

          </div>
        </div>
        <div class="card-block">
          <div class="container-fluid">

            <% if @charge.is_current? %>
              <div class="row" style="margin-bottom: 10px;">
                <%= bold{@entries.count.to_s}%>&nbsp;teams have already entered the&nbsp;<%= bold{@charge.name} %>. <!--Click on a team
                to make a donation through&nbsp;<b>paypal</b>&nbsp;and support conservation in Zambia.-->
              </div>
            <% end %>

            <div class="row">
              <% @entries.each do |entry| %>
                  <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4 col-xl-3">
                    <% if @charge.is_current? %>
                        <%= render :partial => '/teams/teamcard', :locals => {:team => entry.team} %>
                    <% else %>
                        <%= render :partial => '/entries/entrycard', :locals => {:entry => entry} %>
                    <% end %>

                  </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-lg-4">
      <%= render :partial => '/charges/charge_beneficieries', :locals => {:charge => @charge, :grants => @grants} %>
    </div>
  </div>
</div>

app/views/entries/photos.html.erb
<% title('EC ' + @charge.ref + ' ' + @team.long_name) %>

<% breadcrumb [
                  ["charges","Charges"],
                  [charge_path(@charge).sub!('/',''),'Elephant Charge ' + @charge.ref],
                  [charge_entries_path(@charge).sub!('/',''),'Teams'],
                  [entry_path(@entry).sub!('/',''),@team.name],
                  [entry_photos_path(@entry).sub!('/',''),'Photos']
] %>

<div class="container-fluid">
  <div class="row">
    <div class="col">
      <div class="card">
        <div class="card-header">
          <h5 style="display:inline-block;">
            <a href="<%= team_path(@team) %>"><%= @team.long_name %></a> in the <a href="<%= charge_path(@charge) %>"><%= @charge.name %></a>
          </h5>
          <div style="float:right;display: block;">
            <a data-toggle="tooltip" data-placement="bottom" title="Results" href="<%= entry_path(@entry) %>"><img style="margin-left:10px;" src="<%= image_path('icons/grey/results.png')%>"></a>
            <a data-toggle="tooltip" data-placement="bottom" title="Photo Gallery" href="<%= entry_photos_path(@entry) %>"><img style="margin-left:10px;" src="<%= image_path('icons/color/camera.png')%>"></a>
          </div>
        </div>
        <div class="card-block">
          <div class="container-fluid">
            <div class="row">
              <% @entry.photos.each do |photo| %>
                  <div style="padding:5px; " class="col-xs-12 col-sm-6 col-md-4 col-lg-3 col-xl-2">
                    <a href="/photo/<%=photo.id%>?return=<%= entry_photos_path(@entry) %>"><img style="max-width:100%;" class="rounded mx-auto d-block" src="<%= image_path(photo.photo(:medium))%>"></a>
                  </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/entries/show.html.erb
<script src="/Chart.min.js"></script>

<% title('EC ' + @charge.ref + ' ' + @team.long_name) %>

<% breadcrumb [["charges","Charges"],[charge_path(@charge).sub!('/',''),'Elephant Charge ' + @charge.ref],[charge_entries_path(@charge).sub!('/',''),'Teams'],[entry_path(@entry).sub!('/',''),@team.name]] %>
<%
  description= @team.long_name + ' entered their ' + format_position3(@entry.entry_no)  + ' charge in '
  description+= 'a ' + @entry.car.description + ' and completed '
  description+= (@entry.result_description=='Complete' ? ' all ' : '') +  @entry.result_guards.to_s + ' checkpoints in a competition distance of '
  description+= number_with_precision((@entry.dist_competition.nil? ? 0: @entry.dist_competition)/1000.0, precision: 2) +'km, '
  if ! @entry.is_bikes
    description+= 'coming ' + format_position3(@entry.position_distance) + ' out of ' + @charge.entries.count.to_s + ' entries and raising '
  else
    description+= 'coming ' + format_position3(@entry.position_bikes) + ' and raising '
  end 
  description+= '$' + number_with_precision(@entry.raised_dollars, precision: 0, delimiter: ',') + ' for conservation in Zambia.'

  content_for :metas,
              (render :partial => 'layouts/metas', :locals => {
                  :page_title => @team.long_name + ' in the ' + @charge.name,
                  :description => description,
                  :og_image_path => image_path(@team.badge(:original)).split("?")[0]
              })
%>

<div class="container-fluid">
  <div class="row">

    <div class="col-lg-8">
      <div class="card">
        <div class="card-header">
          <h5 style="display:inline-block;">
            <a href="<%= team_path(@team) %>"><%= @team.long_name %></a> in the <a href="<%= charge_path(@charge) %>"><%= @charge.name %></a>
          </h5>
          <div style="float:right;display: block;">
            <a data-toggle="tooltip" data-placement="bottom" title="Results" href="<%= entry_path(@entry) %>"><img style="margin-left:10px;" src="<%= image_path('icons/color/results.png')%>"></a>
            <a data-toggle="tooltip" data-placement="bottom" title="Photo Gallery" href="<%= entry_photos_path(@entry) %>"><img style="margin-left:10px;" src="<%= image_path('icons/grey/camera.png')%>"></a>
          </div>
          <div style="margin-bottom:5px;">
            <%= render :partial => 'application/fbbuttons' %>
          </div>
        </div>
        <div class="card-block">
          <div class="container-fluid">
            <div class="row">
              <div class="col-md-4">
                <%= render :partial => 'photos/photo', :locals => {:photo => @entry.photo_random_landscape} %>
              </div>
              <div class="col-md-8">
                Entered their <%= bold { format_position2(@entry.entry_no) } %> charge in
                a <%= @entry.car.description %> and completed
                <%= @entry.result_description=='Complete' ? ' all ' : '' %><%= @entry.result_guards %> checkpoints in a
                competition distance of
                <%= bold { number_with_precision((@entry.dist_competition.nil? ? 0: @entry.dist_competition)/1000.0, precision: 2) +'km' } %> raising
                <%= bold { '$' + number_with_precision(@entry.raised_dollars, precision: 0, delimiter: ',') } %> for
                conservation in Zambia.
                <ul style="padding-left: 15px;margin-top:10px;">
                  <% @results.each do |result| %>
                      <li><%= result %></li>
                  <% end %>
                </ul>

              </div>
            </div>
          </div>
        </div>
      </div>

      <span><b>Click on a leg below for the details</b></span>
      <table class="table table-sm">
        <% @entry_legs.each_with_index do |el, i| %>
            <tr>
              <td class="high-column">
                <a class="map-selector" data-entry-leg-id="<%= el.id %>" data-toggle="collapse" href="#el_<%= el.id %>" aria-expanded="false" aria-controls="el_<%= el.id %>">
                  <b><%= el.guard_from.name %></b> <%= small_caps { 'to' } %> <b><%= el.guard_to.name %></b>
                  <%= small_caps {el.leg.is_gauntlet ? ' - Gauntlet' : ''}%>
                  <%= small_caps {el.leg.is_tsetse ? ' - Tsetse Line' : ''}%>
                </a>
              </td>
              <td>
                <%= format_position(el.position) %> <%= small_caps { 'of' } %> <%= el.leg.entries.count %>
              </td>
              <td>
                <%= bold { format_meters(el.distance_m) } %> <%= small_caps { 'in' } %> <%= format_seconds(el.elapsed_s) %>

              </td>
            </tr>
            <tr>
              <td class="collapse" colspan="3" id="el_<%= el.id %>">
                <div style="display: inline-block; margin-left:15px;">
                  <%= small_caps { 'Leg no: ' }%><%= i+1 %><br>
                  <%= number_with_precision(el.multiple, precision: 2) %> <%= small_caps { 'times the leg distance of' } %> <%= format_meters(el.leg.distance_m) %><br>
                  <%= small_caps { 'at an average ' } %> <%= number_with_precision(el.speed, precision: 1) %>kmh<br>
                  <%= small_caps { 'over ' } %> <%= format_seconds(el.elapsed_s) %><br>
                  <%= number_with_precision(el.elevation_min, precision: 0, delimiter: ',') %>m <%= small_caps { 'minimum elevation' } %><br>
                  <%= number_with_precision(el.elevation_max, precision: 0, delimiter: ',') %>m <%= small_caps { 'maximum elevation' } %>
                </div>
                <div style="display: inline-block; margin-left:75px;">
                  <% el.leg.entry_legs.order(distance_m: :asc).take(6).each_with_index do |ent_leg,i| %>
                    <%= small_caps{format_position2(i+1)}%>

                    <%=
                      if ent_leg.entry.id==@entry.id
                        bold {ent_leg.entry.name}
                      else
                        ent_leg.entry.name
                      end
                    %>
                    <%= format_meters(ent_leg.distance_m) %><br>
                  <% end %>
                </div>
              </td>
            </tr>
        <% end %>
      </table>
    </div>


    <!-- map -->
    <div class="col-lg-4">
      <div class="col-xs-12 col-sm-12 col-md-6 col-lg-12">
        <div class="card">
          <div class="card-block">
            <div id='map-entry'
                 data-center-lat="<%= @charge.map_center_latitude %>"
                 data-center-lon="<%= @charge.map_center_longitude %>"
                 data-scale="<%= @charge.map_scale %>"
                 data-charge="<%= @charge.ref %>"
                 data-entry="<%= @entry.id %>"
            >
            </div>
          </div>
        </div>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-6 col-lg-12">
        <div class="card">
          <div class="card-block">
            <canvas id="chartElevation" width="400" height="200" data-min-elev="<%= @min_elev %>" data-max-elev="<%= @max_elev %>"></canvas>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>