config/routes.rb
Rails.application.routes.draw do
  root 'application#index'

  get 'sitemap.xml', :to => 'application#sitemap', :defaults => {:format => 'xml'}


  #search
  get 'search', to: 'search#search'

  #flat pages
  get 'about', to: 'application#about'
  get 'contact', to: 'application#contact'
  get 'rules', to: 'application#rules'
  get 'privacy', to: 'application#privacy'
  get 'getinvolved', to: 'application#getinvolved'
  get 'fundraising', to: 'application#fundraising'
  
  get 'compare', to: 'teams#compare'

  #awards
  get 'awards', to: 'application#awards'

  #newsletters
  get 'newsletters', to: 'campaigns#index'

  #standard index routes
  get 'teams', to: 'teams#index'
  get 'charges', to: 'charges#index'
  #get 'sponsors', to: 'sponsors#index'
  get 'beneficiaries', to: 'beneficiaries#index'

  #cars
  get 'cars', to: 'cars#index'
  get 'car/:ref', to: 'cars#show'

  #photos
  get 'photo/:id', to: 'photos#show'
  get 'admin/photo_views', to: 'photos#views'
  get 'photos', to: 'photos#index'

  #JSON STUFF
  get ':id/guards',constraints: {id: /\d{4}/}, to: 'guards#json_index'
  get ':id/entries',constraints: {id: /\d{4}/}, to: 'entries#json_index'
  get 'entry/:entry_id',to: 'entries#json_show'
  get 'entry_legs/:entry_id', to: 'entry_legs#json_index'
  get 'leg/:leg_id',to: 'legs#json_show'

  #charge by year
  get ':id', constraints: {id: /\d{4}/}, to: 'charges#show'

  #charge team list
  get ':id/teams', constraints: {id: /\d{4}/}, to: 'entries#index'

  #charge photos
  get ':id/photos', constraints: {id: /\d{4}/}, to: 'charges#photos'


  #team by name (ref)
  get ':ref', to: 'teams#show'
  get ':ref/photos', to: 'teams#photos'
  #team compare
  get 'compare/:teamone/:teamtwo', to: 'teams#compare'


  #entry by year and team
  get ':id/:ref',constraints: {id: /\d{4}/}, to: 'entries#show'
  get ':id/:ref/photos',constraints: {id: /\d{4}/}, to: 'entries#photos'


  #team by name (ref)
  get 'teams/:id', to: 'teams#show'
  get 'team/:id', to: 'teams#show'

  #charge by year
  get 'charges/:id', to: 'charges#show'
  get 'charge/:id', to: 'charges#show'


  #beneficiary by name (ref)
  get 'beneficiaries/:id', to: 'beneficiaries#show'
  get 'beneficiary/:id', to: 'beneficiaries#show'

  #sponsor by name (ref)
  get 'sponsors/:id', to: 'sponsors#show'
  get 'sponsor/:id', to: 'sponsors#show'

  #cars by id
  get 'cars/:id', to: 'cars#show'
  get 'car/:id', to: 'cars#show'


end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search

    @search=Sunspot.search [Charge,Team,Beneficiary] do
      fulltext params[:q]
    end
    @results=@search.results

  end
end

app/views/search/_beneficiary.html.erb
<span>Beneficiary: <a href="<%= beneficiary_path(ben)%>"><%= ben.name%></a></span>

app/views/search/_charge.html.erb
<span>Charge: <a href="<%= charge_path(charge)%>"><%= charge.long_name%></a></span>

app/views/search/_team.html.erb
<span>Team: <a href="<%= team_path(team)%>"><%= team.name%></a></span>
<span>
  Entries:
  <% team.entries.order(:entry_no).each do |entry| %>
      <% if entry.is_current? %>
    <a href="<%= team_path(entry.team)%>">
      <% else %>
    <a href="<%= entry_path(entry)%>">
      <% end %>

      <%= entry.charge.ref %></a>&nbsp;
  <% end %>
</span>

app/views/search/search.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-10 col-lg-8 col-xl-6">
      <div class="card">
        <div class="card-header">
          <h5><b>Search results for:</b> <%= params[:q]%> (<%= @search.total%> found)</h5>
        </div>
        <div class="card-block">
          <% @results.each do |result| %>
            <div class="card">
              <% if result.class==Charge %>
                  <%= render :partial => '/search/charge', :locals => {:charge => result} %>
              <% end %>
              <% if result.class==Team %>
                  <%= render :partial => '/search/team', :locals => {:team => result} %>
              <% end %>
              <% if result.class==Beneficiary %>
                  <%= render :partial => '/search/beneficiary', :locals => {:ben=> result} %>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>

  </div>
</div>